[package]
name = "dnet-p2p"
version = "0.1.0"
description = "dnet mDNS-based device discovery"
edition = "2021"
authors = ["erhant"]

[lib]
crate-type = [
  "cdylib", # allows C/C++ to use this library
  "rlib",   # allows Rust to use this library
]

[dependencies]
# cli
clap = { version = "4.5.32", features = ["derive"] }

# logging & errors
env_logger = "0.11.7"
log = "0.4.26"
eyre = "0.6.12"

# async
tokio = { version = "1.38", default-features = false, features = ["full"] }
tokio-util = { version = "0.7" }
futures = "0.3.30"

# service discovery
local-ip-address = "0.6.5"

# serialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
