name: build

on:
  push:
    branches: [master]
    paths:
      - "Makefile"
      - "src/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build with Makefile
        run: make
